# k8s/overlays/testing/flask-deploy-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp # Deployment name
spec:
  replicas: 1 # Number of replicas
  template:
    spec:
      containers:
        - name: flaskapp # Container name
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql # Deployment name
spec:
  template:
    spec:
      containers:
        - name: mysql # Container name
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
