apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: flaskapp
        image: yehiashaikhoun/flaskapp:latest
        ports:
        - containerPort: 5002
        env:
        - name: MYSQL_DATABASE_HOST
          value: "mysql"
        - name: MYSQL_DATABASE_USER
          value: "root"
        - name: MYSQL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE_DB
          value: "BucketList"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"