apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      # Init container to wait for MySQL readiness
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL..."
              until nc -z mysql 3306; do
                echo "MySQL not ready, sleeping..."
                sleep 5
              done
              echo "MySQL is up!"
      containers:
        - name: flaskapp
          image: yehiashaikhoun/flaskapp:latest
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: flaskapp-config

          env:
            - name: FLASK_APP
              value: app.py
            - name: MYSQL_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE_PASSWORD

          ports:
            - containerPort: 5002

          readinessProbe:
            httpGet:
              path: /readiness
              port: 5002
            initialDelaySeconds: 40   # allow more time for app to start
            periodSeconds: 10
            failureThreshold: 6       # tolerate 1 min of failures before marking not-ready

          livenessProbe:
            httpGet:
              path: /healthz
              port: 5002
            initialDelaySeconds: 90   # wait longer before checking health
            periodSeconds: 30
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
