# k8s/base/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaskapp
spec:
  ingressClassName: nginx
  rules:
    - host: flaskapp.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flaskapp
                port:
                  number: 80