# k8s/base/kustomization.yaml
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - pvc.yaml
  - ingress.yaml
  - mysql-deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: db-secret
    envs:
      - secrets/db.env